import re,requests,html2text,json,subprocess,time
while(1==1):
    print('╔══╗░░░░╔╦╗░░╔═════╗','╔══╗░░░░╔╦╗░░╔═════╗','╔══╗░░░░╔╦╗░░╔═════╗'' ╔══╗░░░░╔╦╗░░╔═════╗',' ╔══╗░░░░╔╦╗░░╔═════╗','╔═════╗')
    print('║╚═╬════╬╣╠═╗║░▀░▀░║','║╚═╬════╬╣╠═╗║░▀░▀░║','║╚═╬════╬╣╠═╗║░▀░▀░║'' ║╚═╬════╬╣╠═╗║░▀░▀░║',' ║╚═╬════╬╣╠═╗║░▀░▀░║', '║░▀░▀░║')
    print('╠═╗║╔╗╔╗║║║╩╣║╚═══╝║','╠═╗║╔╗╔╗║║║╩╣║╚═══╝║','╠═╗║╔╗╔╗║║║╩╣║╚═══╝║'' ╠═╗║╔╗╔╗║║║╩╣║╚═══╝║',' ╠═╗║╔╗╔╗║║║╩╣║╚═══╝║', '║╚═══╝║')
    print('╚══╩╝╚╝╚╩╩╩═╝╚═════╝','╚══╩╝╚╝╚╩╩╩═╝╚═════╝','╚══╩╝╚╝╚╩╩╩═╝╚═════╝','╚══╩╝╚╝╚╩╩╩═╝╚═════╝',' ╚══╩╝╚╝╚╩╩╩═╝╚═════╝','╚═════╝')
    print('Нажмите 1 если хотите увидеть новости...')
    print('Нажмите 2 чтобы перейти в раздел просмотра курса валют от национального банка РБ...')
    print('Нажмите 3 чтобы перейти в раздел просмотра разной информации...')
    print('Нажмите 4 для того чтобы перейти к панели управления windows :))')
    print('Введите 1.1 что-бы выйти из системы,1.2 для того чтобы выйти из программы')
    print('                               [[[[       все данные в режиме *LIVE*       ]]]]')
    g=input('///')
    print('///',g,'///')
    if(g=='1.2'):
        break
    if(g=='1.1'):
        print('EXIT WITH SYSTEM')
        time.sleep(1)
        print('loading module...')
        time.sleep(1)
        print('10')
        time.sleep(0.15)
        print('9')
        time.sleep(0.15)
        print('8')
        time.sleep(0.15)
        print('7')
        time.sleep(0.15)
        print('6')
        time.sleep(0.15)
        print('5')
        time.sleep(0.15)
        print('4')
        time.sleep(0.15)
        print('3')
        time.sleep(0.15)
        print('2')
        time.sleep(0.15)
        print('1')
        time.sleep(0.15)
        print('MODULE COMPETED!')
        time.sleep(2)
        subprocess.call(["shutdown", "/l"])
        break
    if(g == '1' ):
        while(1==1):
            s=requests.get('http://m.news.yandex.ru')
            d = html2text.HTML2Text().handle(s.text)
            print(d)
            ghg=int(input('НАЖМИТЕ 1 ЧТОБЫ УВИДЕТЬ ВСЕ АДРЕСАТЫ ИЗ НОВОСТЕЙ.(@GMAIL.COM,@MAIL.RU)'))
            if(ghg==1):
                pattern=r"\b\w+@gmail.com"
                pattern1=r"\b\w+@mail.ru"
                string=d
                result=re.findall(pattern,string)
                result1=re.findall(pattern1,string)
                print(result,result1)
                plsss=input('Введите любое значение для закрыти...')
            else:
                time.sleep(16)
                break
            time.sleep(16)
            break
    if(g == '3'):
        print(' ＜￣｀ヽ、　　　　　　　／￣＞ ')
        print('　ゝ、　　＼　／⌒ヽ,ノ 　/´ ')
        print('　　　ゝ、　`（ ( ͡° ͜ʖ ͡°) ／ ')
        print('　　 　　>　 　 　,ノ 　 ')
        print('　　　　　∠_,,,/´”')
    
        print('  НОВОСТИ')
        print('1 - "Белорусская АЭС заработала, но западные страны объявили ей бойкот"')
        print('2 - "SpaceX"')
        print('3 - "Космос"')
        print('4 - "Мир игр"')
        print('0 - "Выход"')
        while(1==1):
            kl=int(input())
            if(kl == 1):
                sfg=requests.get('https://www.bbc.com/russian/news-54796354')
                ddf= html2text.HTML2Text().handle(sfg.text)
                print(ddf)
                print('  НОВОСТИ')
                print('1 - "Белорусская АЭС заработала, но западные страны объявили ей бойкот"')
                print('2 - "SpaceX"')
                print('3 - "Космос"')
                print('4 - "Мир игр"')
                print('0 - "Выход"')
            if(kl == 2):
                sfg3=requests.get('https://ria.ru/organization_Space_Exploration_Technologies/')
                ddf3= html2text.HTML2Text().handle(sfg3.text)
                print(ddf3)
                print('  НОВОСТИ')
                print('1 - "Белорусская АЭС заработала, но западные страны объявили ей бойкот"')
                print('2 - "SpaceX"')
                print('3 - "Космос"')
                print('4 - "Мир игр"')
                print('0 - "Выход"')
            if(kl == 3):
                sfg4=requests.get('https://rg.ru/tema/obshestvo/kosmos/')
                ddf4= html2text.HTML2Text().handle(sfg4.text)
                print(ddf4)
                print('  НОВОСТИ')
                print('1 - "Белорусская АЭС заработала, но западные страны объявили ей бойкот"')
                print('2 - "SpaceX"')
                print('3 - "Космос"')
                print('4 - "Мир игр"')
                print('0 - "Выход"')
            if(kl == 4):
                while(1==1):
                    print('1 - Steam store')
                    print('2 - CS:GO')
                    print('3 - DOTA2')
                    print('4 - FACEIT')
                    print('5 - CS.MONEY (market)')
                    print('6 - OTHER ')
                    print('0 - Exit')
                    qwe=int(input())
                    if(qwe==1):
                        steam=requests.get('https://store.steampowered.com/')
                        steam1=html2text.HTML2Text().handle(steam.text)
                        print(steam1)
                    if(qwe==2):
                        cs=requests.get('https://csgohub.ru/csgo-updates/')
                        cs1=html2text.HTML2Text().handle(cs.text)
                        print('UPDATE',cs1)
                        cscs=requests.get('https://cyber.sports.ru/cs/news/')
                        cscs1=html2text.HTML2Text().handle(cscs.text)
                        print('NEWS',cscs1)
                    if(qwe==3):
                        dota=requests.get('http://www.dota2.com/news/updates/?l=russian')
                        dota1=html2text.HTML2Text().handle(dota.text)
                        print('UPDATE',dota1)
                        ddota=requests.get('https://cyber.sports.ru/games/dota-2/')
                        ddota1=html2text.HTML2Text().handle(ddota.text)
                        print('NEWS',ddota1)
                    if(qwe==4):
                        faceit=requests.get('https://cyber.sports.ru/cs/tournament/faceit/news/')
                        faceit1=html2text.HTML2Text().handle(faceit.text)
                        print('NEWS - ',faceit1)
                    if(qwe==5):
                        money=request.get('https://cs.money/ru/csgo/store/')
                        money1=html2text.HTML2Text().handle(money.text)
                        print(money1)
                    if(qwe==6):
                        more=request.get('https://shazoo.ru/tags/419/games')
                        more1=html2text.HTML2Texr().handle(money.text)
                        print(more1)
                    if(qwe==0):
                        print('  НОВОСТИ')
                        print('1 - "Белорусская АЭС заработала, но западные страны объявили ей бойкот"')
                        print('2 - "SpaceX"')
                        print('3 - "Космос"')
                        print('4 - "Мир игр"')
                        print('0 - "Выход"')
                        break

            if(kl == 0):
                print('Exit')
                time.sleep(3)
                break
    
    
    if(g > '4')or(g < '1'):
        print('Знаете... ')
        time.sleep(1)
        print('Мне от части вас жаль...')
        time.sleep(1.5)
        print('Спросите  - почему?')
        gfgf=str(input('--'))
        time.sleep(1.5)
        print('Хех,всё просто!')
        time.sleep(1)
        print('Вы ввели значения которых нет во всех пунктах и вы можете подумать - почему программа не выдала ошибку и почему она продолжает свою работу? Дело в том... что я продумал такой исход событий и поэтому щас пк офнится:)))')
        time.sleep(10)
        print('LOOOOL, Я вас обманул:))')
        time.sleep(1)
        print('ИСПУГАЛИСЬ??')
        time.sleep(5)
        print('А не зря...')
        time.sleep(3)
        print('У вас есть 30 секунд чтобы решить пример если ваша попытка увенчается фэйлом то тогда прощайте...Попытка только одна!!')
        time.sleep(4)
        subprocess.call(["shutdown","/s","/t", "30"]) #////////////////////////
        xc=int(input('ПОЕХАЛИ...33*33='))
        if(xc == 1089):
            subprocess. call(["shutdown", "/a"])#//////////////////////////
            print('ВЫ СМОГЛИ!!! УРАААА и да, я не шутил...')
            time.sleep(15)
        else:
            print('Мне жаль,ответ не верный!')
    if(g == '2' ):
        time.sleep(1)
        print('ЗАГРУЗКА...')
        time.sleep(0.12)
        print('░░░░░▄▄▀▀▀▀▀▀▀▀▀▄▄░░░',)
        time.sleep(0.12)
        print('░░░░█░░░░░░░░░░░░░█░░',)
        time.sleep(0.12)
        print('░░░█░░░░░░░░░░▄▄▄░░█░',)
        time.sleep(0.12)
        print('░░░█░░▄▄▄░░▄░░███░░█░',)
        time.sleep(0.12)
        print('░░░▄█░▄░░░▀▀▀░░░▄░█▄░',)
        time.sleep(0.12)
        print('░░░█░░▀█▀█▀█▀█▀█▀░░█░',)
        time.sleep(0.12)
        print('░░░▄██▄▄▀▀▀▀▀▀▀▄▄██▄░',)
        time.sleep(0.12)
        print('████████████████████████')
        time.sleep(0.12)
        print('████████████████████████')
        time.sleep(0.12)
        print('████████████████████████')
        time.sleep(0.12)
        print('████████████████████████')
        time.sleep(0.12)
        print('████████████████████████')
        time.sleep(0.12)
        print('████████████████████████')
        time.sleep(0.12)
        print('████████████████████████')
        time.sleep(0.12)
        print('████████████████████████')
        time.sleep(0.12)
        print('████████████████████████')





        print('      КУРС ВАЛЮТ     ')
        print('1 - Доллара США.')
        print('2 - Евро.')
        print('3 - Гривна.')
        print('4 - Российский рубль.')
        print('5 - Китайский нюань.')
        print('6 - Прочие валюты(Не разделено!).')
        print('0 - ВЫХОД.')
        while(1==1):
            l=int(input())
            if(l == 1 ):
                sd=requests.get('https://www.nbrb.by/api/exrates/rates/145')
                dolar=sd.json()
                print(dolar)
            if(l == 3):
                sdd=requests.get('https://www.nbrb.by/api/exrates/rates/290')
                ukraina=sdd.json()
                print(ukraina)
            if(l == 2):
                sdd1=requests.get('https://www.nbrb.by/api/exrates/rates/292')
                eur=sdd1.json()
                print(eur)
            if(l == 4):
                rusa=requests.get('https://www.nbrb.by/api/exrates/rates/298')
                russian=rusa.json()
                print(russian)        
            if(l == 5):
                kir=requests.get('https://www.nbrb.by/api/exrates/rates/304')
                kir12=kir.json()
                print(kir12)
            if(l == 6 ):
                vse=requests.get('https://www.nbrb.by/api/exrates/rates?periodicity=0')
                vse12=vse.json()
                print(vse12)
            if(l== 0):

                print('GOODBYE')
                break

    if(g == '4'):
     while(1==1):
        print('    **ПАНЕЛЬ УПРОВЛЕНИЯ**')
        print('1 - ПЕРЕЗАГРУЗКА')
        print('2 - ВЫЙТИ ИЗ СИСТЕМЫ')
        print('3 - НЕМЕДЛЕННОЕ ВЫКЛЮЧЕНИЕ')
        print('4 - ВЫКЛЮЧЕНИЕ ЧЕРЕЗ 60 СЕКУНД')
        print('5 - ОТМЕНА ВЫКЛЮЧЕНИЯ')
        print('0 - ВЕРНУТСЯ')
        off=int(input())
        if(off==1):##
            print('you select - REBOOT')
            time.sleep(1)
            print('loading module...')
            time.sleep(1)
            print('10')
            time.sleep(0.15)
            print('9')
            time.sleep(0.15)
            print('8')
            time.sleep(0.15)
            print('7')
            time.sleep(0.15)
            print('6')
            time.sleep(0.15)
            print('5')
            time.sleep(0.15)
            print('4')
            time.sleep(0.15)
            print('3')
            time.sleep(0.15)
            print('2')
            time.sleep(0.15)
            print('1')
            time.sleep(0.15)
            print('MODULE COMPETED!')
            time.sleep(2)
            subprocess.call(["shutdown", "/r"])
        if(off==2):##
            print('you select - EXIT To SYSTEM')
            time.sleep(1)
            print('loading module...')
            time.sleep(1)
            print('10')
            time.sleep(0.15)
            print('9')
            time.sleep(0.15)
            print('8')
            time.sleep(0.15)
            print('7')
            time.sleep(0.15)
            print('6')
            time.sleep(0.15)
            print('5')
            time.sleep(0.15)
            print('4')
            time.sleep(0.15)
            print('3')
            time.sleep(0.15)
            print('2')
            time.sleep(0.15)
            print('1')
            time.sleep(0.15)
            print('MODULE COMPETED!')
            time.sleep(2)
            subprocess.call(["shutdown", "/l"]) 
        if(off==3):##
            print('you select - POWEROFF (NO TIMER)')
            time.sleep(1)
            print('loading module...')
            time.sleep(1)
            print('10')
            time.sleep(0.15)
            print('9')
            time.sleep(0.15)
            print('8')
            time.sleep(0.15)
            print('7')
            time.sleep(0.15)
            print('6')
            time.sleep(0.15)
            print('5')
            time.sleep(0.15)
            print('4')
            time.sleep(0.15)
            print('3')
            time.sleep(0.15)
            print('2')
            time.sleep(0.15)
            print('1')
            time.sleep(0.15)
            print('MODULE COMPETED!')
            time.sleep(2)
            subprocess.call(["shutdown","/s"])
        if(off==4):##
            print('you select - POWEROFF (which timer 60sec)')
            time.sleep(1)
            print('loading module...')
            time.sleep(1)
            print('10')
            time.sleep(0.15)
            print('9')
            time.sleep(0.15)
            print('8')
            time.sleep(0.15)
            print('7')
            time.sleep(0.15)
            print('6')
            time.sleep(0.15)
            print('5')
            time.sleep(0.15)
            print('4')
            time.sleep(0.15)
            print('3')
            time.sleep(0.15)
            print('2')
            time.sleep(0.15)
            print('1')
            time.sleep(0.15)
            print('MODULE COMPETED!')
            time.sleep(2)
            subprocess.call(["shutdown","/s","/t", "60"])
        if(off==5):##
            print('you select - back operation')
            time.sleep(1)
            print('loading module...')
            time.sleep(1)
            print('10')
            time.sleep(0.15)
            print('9')
            time.sleep(0.15)
            print('8')
            time.sleep(0.15)
            print('7')
            time.sleep(0.15)
            print('6')
            time.sleep(0.15)
            print('5')
            time.sleep(0.15)
            print('4')
            time.sleep(0.15)
            print('3')
            time.sleep(0.15)
            print('2')
            time.sleep(0.15)
            print('1')
            time.sleep(0.15)
            print('MODULE COMPETED!')
            time.sleep(2)
            subprocess. call(["shutdown", "/a"])
        if(off==0):##
            print('completed!')
            break
